<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" file="example_hello_tests.py" name="example_hello_tests.HelloWorldTest-20190925040728" skipped="0" tests="1" time="0.001" timestamp="2019-09-25T04:07:28">
	<testcase classname="example_hello_tests.HelloWorldTest" file="src/unittest/python/example_hello_tests.py" line="9" name="test_correct_message" time="0.001" timestamp="2019-09-25T04:07:28">
		<error message="global name 'mock' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/home/michael/MyPythonProject/src/unittest/python/example_hello_tests.py", line 10, in test_correct_message
    out = mock()
NameError: global name 'mock' is not defined
]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
